/** The grammar bits, as data: every rule GRAMMAR.md's tables list.
 *
 *  A rule here is a bit the learner can open on the Grammar screen and be
 *  asked in a sitting; its id is the record's id for ever, and the document
 *  is the one place a rule is described in prose. This file is generated
 *  from the document's tables and kept equal to them by
 *  tests/grammar-rules.test.ts, which parses the document itself: a rule
 *  added, renamed or re-wired in one and not the other fails there. Do not
 *  edit the rows by hand; edit GRAMMAR.md and regenerate
 *  (scripts/grammar-rules.py).
 *
 *  `needs` is what a rule builds on and `after` the order learners are
 *  observed to take; both are advice the screen states, never a lock: every
 *  bit is opt-in, and the learner picks. `faces` is how the rule is
 *  practised (GRAMMAR.md, "Generators, faces, and how many at once"), and
 *  `placed` where the syllabus and Kwiziq put it.
 */

/** The ten modules of the inventory, by the letter of their ids. */
export type Module = "sounds" | "numbers" | "nouns" | "adjectives" | "pronouns" | "verbs" | "negation" | "questions" | "connectors" | "sentences";

/** How a rule is put in front of the learner. */
export type Face = "read" | "choose" | "gap" | "which" | "say" | "hear" | "transform" | "order" | "mark" | "spell";

export interface RuleSpec {
  readonly module: Module;
  /** The rule in one sentence, as the document's table states it. */
  readonly what: string;
  readonly needs: readonly string[];
  readonly after: readonly string[];
  readonly faces: readonly Face[];
  readonly placed: string;
}

export const RULES = {
  "P.letters": {
    module: "sounds",
    what: "The alphabet and the five accents: what é, è, ê, ç and the tréma do to a sound; spelling a word aloud",
    needs: [],
    after: [],
    faces: ["hear", "say"],
    placed: "A1",
  },
  "P.final": {
    module: "sounds",
    what: "Final consonants are silent except *c, r, f, l* — and the exceptions that matter (*-er* infinitives, *blanc, porc, tabac, gentil*)",
    needs: ["P.letters"],
    after: [],
    faces: ["mark"],
    placed: "— (FI phonetics)",
  },
  "P.e-caduc": {
    module: "sounds",
    what: "The *e* that drops: *samedi, je ne sais pas → j'sais pas*; kept when three consonants would meet",
    needs: ["P.final"],
    after: [],
    faces: ["mark", "hear"],
    placed: "— (FI phonetics)",
  },
  "P.nasal": {
    module: "sounds",
    what: "The nasal vowels *an/en, on, in/ain/ein, un* (Swiss French keeps *un* distinct), and the *n* that comes back before a vowel or a written *n*: *bon / bonne, an / année*",
    needs: ["P.letters"],
    after: [],
    faces: ["hear", "say"],
    placed: "— (FI phonetics)",
  },
  "P.vowel-pairs": {
    module: "sounds",
    what: "*u* against *ou*; *é* against *è* (kept apart in Swiss French at the end of a word: *j'irai / j'irais*); *o* open and closed; *eu* open and closed",
    needs: ["P.letters"],
    after: [],
    faces: ["hear"],
    placed: "— (FI phonetics)",
  },
  "P.semi": {
    module: "sounds",
    what: "The semi-vowels *oi, ui, ill, y*: *lui, fille, travail, voyage*",
    needs: ["P.letters"],
    after: [],
    faces: ["hear", "say"],
    placed: "— (FI phonetics)",
  },
  "P.r-h": {
    module: "sounds",
    what: "The French *r*; mute *h* against aspirated *h* (*l'homme* but *le héros*), and that the dictionary marks which",
    needs: ["P.letters"],
    after: [],
    faces: ["choose"],
    placed: "— (FI phonetics)",
  },
  "P.elision": {
    module: "sounds",
    what: "Elision: *je, me, te, se, le, la, ne, de, que, ce* lose their vowel before a vowel; *si* only before *il(s)*; never before an aspirated *h*, *onze*, *oui*",
    needs: ["P.r-h"],
    after: [],
    faces: ["mark", "gap"],
    placed: "A1 (implicit in every article bit)",
  },
  "P.enchaine": {
    module: "sounds",
    what: "Enchaînement: a said final consonant moves onto the next vowel, *il est / i-lest*, *une amie / u-namie*",
    needs: ["P.final"],
    after: [],
    faces: ["mark", "say"],
    placed: "— (FI phonetics)",
  },
  "P.liaison-must": {
    module: "sounds",
    what: "Obligatory liaison: determiner + noun, adjective + noun, pronoun + verb, verb + pronoun in inversion, after *en, dans, chez, très, plus* and in set phrases; *s/x → z, d → t, f → v* in *neuf ans / neuf heures*, *n* with the nasal kept in *mon ami* and lost in *bon ami*",
    needs: ["P.enchaine", "P.nasal"],
    after: [],
    faces: ["mark", "say"],
    placed: "A2 (Inventaire: \"liaisons\")",
  },
  "P.liaison-never": {
    module: "sounds",
    what: "Forbidden liaison: after *et*, after a singular noun, before an aspirated *h*, before *onze* and *oui*, after *quand* and *comment* as question words (except *quand est-ce que*, *comment allez-vous*)",
    needs: ["P.liaison-must"],
    after: [],
    faces: ["mark"],
    placed: "—",
  },
  "P.liaison-may": {
    module: "sounds",
    what: "Optional liaison and register: plural noun + verb, *est* + complement, *pas* + vowel; more in reading aloud, fewer in speech",
    needs: ["P.liaison-never"],
    after: [],
    faces: ["which"],
    placed: "—",
  },
  "P.verb-endings": {
    module: "sounds",
    what: "What verb endings sound like: *-ent* is silent (*il parle = ils parlent*), *-er, -ez, -é, -ai* are all /e/, *-ais, -ait, -aient* are /ɛ/, *-ons* and *-ont* are the same nasal; so *ils ont / ils sont* is a liaison, *z* against *s*",
    needs: ["P.final", "P.liaison-must", "V.pres-er"],
    after: [],
    faces: ["hear", "mark"],
    placed: "— (needed by every tense bit)",
  },
  "P.plural-heard": {
    module: "sounds",
    what: "Plural is heard on the article and the liaison, not the noun: *les amis* /lez‿ami/, *ils aiment* /ilz‿ɛm/; *il aime* and *ils aiment* differ only there",
    needs: ["P.liaison-must", "D.plural"],
    after: [],
    faces: ["hear"],
    placed: "— (Bartning & Schlyter: last to stabilise)",
  },
  "P.questions": {
    module: "sounds",
    what: "Intonation of a yes/no question; rhythm and final stress of a phrase, against English word stress",
    needs: ["P.letters"],
    after: [],
    faces: ["hear", "say"],
    placed: "A1–B2 (Inventaire: \"rythme / intonation\")",
  },
  "N.units": {
    module: "numbers",
    what: "Zero to sixteen as items: *un / une* agrees, the rest do not; *onze* to *seize* are one word each",
    needs: ["P.letters"],
    after: [],
    faces: ["hear", "spell", "say"],
    placed: "A1",
  },
  "N.teens": {
    module: "numbers",
    what: "Seventeen to nineteen are *dix* + unit with a hyphen: *dix-sept, dix-huit, dix-neuf*",
    needs: ["N.units"],
    after: [],
    faces: ["spell", "hear"],
    placed: "A1",
  },
  "N.tens": {
    module: "numbers",
    what: "The tens as items: *vingt, trente, quarante, cinquante, soixante, septante, huitante, nonante*",
    needs: ["N.units"],
    after: [],
    faces: ["hear", "spell", "say"],
    placed: "A1",
  },
  "N.tens-units": {
    module: "numbers",
    what: "A ten and a unit join with a hyphen: *vingt-deux, huitante-quatre, nonante-neuf*",
    needs: ["N.tens"],
    after: [],
    faces: ["spell", "hear"],
    placed: "A1",
  },
  "N.et-un": {
    module: "numbers",
    what: "*et un* — no hyphen in the traditional spelling, hyphens throughout since 1990, both accepted — at twenty-one and every tens-plus-one up to *nonante et un*; *et une* before a feminine noun",
    needs: ["N.tens-units"],
    after: [],
    faces: ["spell"],
    placed: "A1",
  },
  "N.french-tens": {
    module: "numbers",
    what: "Recognising the French compounds: *soixante-dix* to *soixante-dix-neuf* is sixty plus a teen, *quatre-vingts* to *quatre-vingt-dix-neuf* is eighty plus a number under twenty; *soixante et onze*, *quatre-vingt-un* without *et*; *quatre-vingts* keeps its *s* only when it ends the number",
    needs: ["N.et-un"],
    after: [],
    faces: ["hear", "which"],
    placed: "A1 (Kwiziq: \"70 to 999\")",
  },
  "N.cent": {
    module: "numbers",
    what: "*cent* multiplies and never takes *un*; it takes an *s* only when it is multiplied *and* ends the number: *cent un, deux cents, deux cent un*",
    needs: ["N.tens-units"],
    after: [],
    faces: ["spell"],
    placed: "A1",
  },
  "N.mille": {
    module: "numbers",
    what: "*mille* never varies and never takes *un*: *mille, deux mille, mille un*; *deux mille vingt-six* in a date",
    needs: ["N.cent"],
    after: [],
    faces: ["spell"],
    placed: "A1",
  },
  "N.million": {
    module: "numbers",
    what: "*million* and *milliard* are nouns: they take *un*, an *s*, and *de* before what they count — *un million de personnes, deux milliards d'euros*; *deux millions trois cent mille*",
    needs: ["N.mille"],
    after: [],
    faces: ["spell"],
    placed: "A1",
  },
  "N.sandhi": {
    module: "numbers",
    what: "The numbers that change sound: *six* and *dix* are /sis/ /dis/ alone, /si/ /di/ before a consonant, /siz/ /diz/ before a vowel; *huit* loses its *t* before a consonant; *neuf* is /nœv/ in *neuf ans* and *neuf heures* only; *vingt* sounds its *t* in *vingt et un* to *vingt-neuf* and before a vowel; *cent* liaises (*cent ans*) but not in *cent un*; *deux, trois* liaise in *z*; *quatre-vingts ans* liaises in *z*, never *t*; no liaison or elision before *huit* and *onze*",
    needs: ["N.french-tens", "N.cent", "P.liaison-must"],
    after: [],
    faces: ["say", "hear"],
    placed: "— (needed by everything below)",
  },
  "N.ordinal": {
    module: "numbers",
    what: "Ordinals: *premier / première*, then *-ième* on the cardinal (*quatrième* drops the *e*, *cinquième* adds a *u*, *neuvième* turns *f* to *v*); written *1er, 1re, 2e*; *premier* for the first of the month and the first king, cardinals after that (*le deux mai, Louis quatorze*), ordinals for floors and centuries",
    needs: ["N.units"],
    after: [],
    faces: ["spell", "gap"],
    placed: "A1",
  },
  "N.time": {
    module: "numbers",
    what: "Telling the time: *il est une heure*, *heure(s)* always said, *et quart, et demie, moins le quart, moins dix*, *midi et demi*; the 24-hour clock for timetables, *quinze heures trente*",
    needs: ["N.tens-units"],
    after: [],
    faces: ["hear", "spell", "say"],
    placed: "A1",
  },
  "N.date": {
    module: "numbers",
    what: "Dates: *le premier mai* but *le deux mai*, *en deux mille quinze*, *jeudi 3 septembre* with no capitals, *on est le combien ?*",
    needs: ["N.mille", "N.ordinal"],
    after: [],
    faces: ["spell", "gap"],
    placed: "A1",
  },
  "N.prices": {
    module: "numbers",
    what: "Prices and measures: *trois francs cinquante*, *un euro vingt*, *deux kilos de*, *à dix kilomètres*, *moins dix pour cent*",
    needs: ["N.cent"],
    after: [],
    faces: ["hear", "spell"],
    placed: "A1 (Inventaire: \"quantités et mesures\")",
  },
  "N.age-duration": {
    module: "numbers",
    what: "Age and spans: *j'ai trente ans* (avoir, never être), *depuis trois ans, pendant deux heures, il y a dix ans, dans une semaine*",
    needs: ["N.tens-units", "C.time-markers"],
    after: [],
    faces: ["gap"],
    placed: "A1–A2",
  },
  "N.phone": {
    module: "numbers",
    what: "Phone numbers, read in groups: *079 123 45 67* in Switzerland (*zéro septante-neuf, cent vingt-trois, quarante-cinq, soixante-sept*), pairs in France",
    needs: ["N.cent"],
    after: [],
    faces: ["hear", "say"],
    placed: "— (an A1 function: donner des informations personnelles)",
  },
  "N.approx": {
    module: "numbers",
    what: "Roughly: *une dizaine, une douzaine, une quinzaine, une vingtaine, une centaine, un millier* + *de*; *environ, à peu près, presque*",
    needs: ["N.cent"],
    after: [],
    faces: ["gap", "choose"],
    placed: "A2",
  },
  "N.fractions": {
    module: "numbers",
    what: "Halves and parts: *demi* (agrees after the noun, invariable before it: *une heure et demie, une demi-heure*), *la moitié de, un tiers, un quart, trois cinquièmes*; decimals with a comma, *deux virgule cinq*; percentages",
    needs: ["N.ordinal"],
    after: [],
    faces: ["spell", "hear"],
    placed: "A2–B1",
  },
  "N.arith": {
    module: "numbers",
    what: "Arithmetic aloud: *et / plus, moins, fois, divisé par, font / égale*; the **hear** face where the answer must be computed, so the number was understood and not just transcribed",
    needs: ["N.cent"],
    after: [],
    faces: ["hear"],
    placed: "A2 (Kwiziq)",
  },
  "D.gender": {
    module: "nouns",
    what: "Every noun has a gender and the article carries it; *le / la / l'*, *un / une*",
    needs: ["P.elision"],
    after: [],
    faces: ["choose"],
    placed: "A1",
  },
  "D.gender-endings": {
    module: "nouns",
    what: "Gender from the ending, for the endings that predict it: *-tion, -té, -ette, -ance, -ure, -ie* feminine; *-age, -ment, -eau, -isme, -oir* masculine; the famous exceptions",
    needs: ["D.gender"],
    after: [],
    faces: ["which"],
    placed: "A1 (Kwiziq)",
  },
  "D.plural": {
    module: "nouns",
    what: "Plural: *-s* unheard; *-x* after *-au, -eau, -eu*; *-al → -aux*; *-ou* (*bijoux*); nouns already in *-s, -x, -z*; surnames do not pluralise",
    needs: ["D.gender"],
    after: [],
    faces: ["gap", "hear"],
    placed: "A1",
  },
  "D.art-def": {
    module: "nouns",
    what: "The definite article: generalising (*j'aime le café*), days and dates (*le lundi*), body parts, languages, titles, countries",
    needs: ["D.gender"],
    after: [],
    faces: ["choose", "gap"],
    placed: "A1",
  },
  "D.art-indef": {
    module: "nouns",
    what: "The indefinite and the partitive: *un, une, des*; *du, de la, de l'* for some of; *des* against *les*",
    needs: ["D.art-def"],
    after: [],
    faces: ["choose"],
    placed: "A1",
  },
  "D.contract": {
    module: "nouns",
    what: "*à* and *de* fuse with *le* and *les*: *au, aux, du, des*",
    needs: ["D.art-def"],
    after: [],
    faces: ["gap"],
    placed: "A1",
  },
  "D.de-negative": {
    module: "nouns",
    what: "After a negation, *un / une / du / des* become *de*: *je n'ai pas de voiture*; not after *être*",
    needs: ["D.art-indef", "G.pas"],
    after: [],
    faces: ["gap"],
    placed: "A1",
  },
  "D.de-quantity": {
    module: "nouns",
    what: "After a quantity, *de* alone: *beaucoup de, un peu de, un kilo de, trop de, assez de, plus de*; *la plupart des*",
    needs: ["D.de-negative"],
    after: [],
    faces: ["gap"],
    placed: "A1",
  },
  "D.de-adjective": {
    module: "nouns",
    what: "*des* becomes *de* before a plural adjective + noun: *de belles maisons*",
    needs: ["D.de-quantity", "J.position"],
    after: [],
    faces: ["gap"],
    placed: "B1",
  },
  "D.possessive": {
    module: "nouns",
    what: "*mon, ma, mes …*; *mon* before a feminine vowel (*mon amie*); *son* for his and her alike; *leur* against *leurs*",
    needs: ["D.gender"],
    after: [],
    faces: ["gap"],
    placed: "A1",
  },
  "D.demonstrative": {
    module: "nouns",
    what: "*ce, cet, cette, ces*; *cet* before a vowel; *-ci* and *-là* to tell two apart",
    needs: ["D.possessive"],
    after: [],
    faces: ["gap"],
    placed: "A1–A2",
  },
  "D.tout": {
    module: "nouns",
    what: "*tout / toute / tous / toutes* as a determiner: *tous les jours, toute la journée*",
    needs: ["D.plural"],
    after: [],
    faces: ["gap"],
    placed: "A2",
  },
  "D.indef-det": {
    module: "nouns",
    what: "*chaque, plusieurs, quelques, certains, aucun, n'importe quel, autre*",
    needs: ["D.tout"],
    after: [],
    faces: ["choose"],
    placed: "A2–B1",
  },
  "D.c-est": {
    module: "nouns",
    what: "*c'est* against *il est / elle est*: *c'est* before a determiner or a name, *il est* before a bare adjective, nationality or job",
    needs: ["D.art-indef"],
    after: [],
    faces: ["choose"],
    placed: "A1",
  },
  "D.il-y-a": {
    module: "nouns",
    what: "*il y a* and *voilà / voici* for pointing at what exists",
    needs: ["D.art-indef"],
    after: [],
    faces: ["gap"],
    placed: "A1",
  },
  "D.countries": {
    module: "nouns",
    what: "Countries and cities take their article and preposition by gender: *en France, au Portugal, aux États-Unis, à Sion, en Suisse*; the canton is *le Valais* but *en Valais*",
    needs: ["D.contract"],
    after: [],
    faces: ["choose"],
    placed: "A1",
  },
  "J.agree": {
    module: "adjectives",
    what: "Adjectives agree: *-e* for feminine (none if already *-e*), *-s* for plural; *grand / grande / grands / grandes*",
    needs: ["D.gender", "D.plural"],
    after: [],
    faces: ["gap"],
    placed: "A1",
  },
  "J.fem-irregular": {
    module: "adjectives",
    what: "Feminine by rule: *-eux → -euse, -er → -ère, -f → -ve, -ien → -ienne, -el → -elle, -et → -ète / -ette, -c → -che / -que*; and the ones to learn as items (*long, frais, faux, doux, sec, gentil, favori, grec*)",
    needs: ["J.agree"],
    after: [],
    faces: ["gap"],
    placed: "A1–A2",
  },
  "J.plural-x": {
    module: "adjectives",
    what: "Plural in *-x*: *-al → -aux* (*banals* excepted), *-eau → -eaux*; *-s, -x* unchanged",
    needs: ["J.agree"],
    after: [],
    faces: ["gap"],
    placed: "A2–B1",
  },
  "J.position": {
    module: "adjectives",
    what: "Most adjectives follow the noun; the short common ones go before (*beau, bon, grand, gros, jeune, joli, mauvais, nouveau, petit, vieux*)",
    needs: ["J.agree"],
    after: [],
    faces: ["order"],
    placed: "A1",
  },
  "J.beau": {
    module: "adjectives",
    what: "*beau / bel / belle, nouveau / nouvel / nouvelle, vieux / vieil / vieille* before a vowel",
    needs: ["J.position", "P.elision"],
    after: [],
    faces: ["gap"],
    placed: "A1",
  },
  "J.meaning-position": {
    module: "adjectives",
    what: "An adjective that changes meaning with its place: *un ancien collègue / un bâtiment ancien, ma propre voiture / une voiture propre, un certain âge / une réponse certaine*",
    needs: ["J.position"],
    after: [],
    faces: ["which"],
    placed: "B1",
  },
  "J.colours": {
    module: "adjectives",
    what: "Colours: agree, except those named after things (*orange, marron*) and compounds (*bleu clair*)",
    needs: ["J.agree"],
    after: [],
    faces: ["gap"],
    placed: "A1–B1",
  },
  "J.compare": {
    module: "adjectives",
    what: "Comparing: *plus … que, moins … que, aussi … que* with adjectives and adverbs; *plus de … que* with nouns; *autant que* with verbs",
    needs: ["J.agree"],
    after: [],
    faces: ["transform"],
    placed: "A2",
  },
  "J.superlative": {
    module: "adjectives",
    what: "The superlative: *le plus …, le moins …*, the article repeated after the noun (*la ville la plus belle*); *de* for \"in\"",
    needs: ["J.compare"],
    after: [],
    faces: ["transform"],
    placed: "A2",
  },
  "J.bon-bien": {
    module: "adjectives",
    what: "*bon / meilleur / le meilleur* against *bien / mieux / le mieux*; *mauvais / pire*",
    needs: ["J.compare"],
    after: [],
    faces: ["choose"],
    placed: "A2–B1",
  },
  "J.adverb-ment": {
    module: "adjectives",
    what: "Adverbs in *-ment*: from the feminine (*lentement*), from the vowel masculine (*vraiment*), *-ant / -ent → -amment / -emment*; the irregular set (*bien, mal, vite, mieux*)",
    needs: ["J.fem-irregular"],
    after: [],
    faces: ["gap"],
    placed: "A1–A2",
  },
  "J.adverb-position": {
    module: "adjectives",
    what: "Where the adverb goes: after the verb in a simple tense, between auxiliary and participle in a compound one for the short ones (*déjà, toujours, bien, beaucoup*)",
    needs: ["J.adverb-ment", "V.pc"],
    after: [],
    faces: ["order"],
    placed: "A2",
  },
  "J.more-and-more": {
    module: "adjectives",
    what: "*de plus en plus, de moins en moins, plus … plus …*",
    needs: ["J.compare"],
    after: [],
    faces: ["gap"],
    placed: "A2–B1",
  },
  "R.subject": {
    module: "pronouns",
    what: "Subject pronouns; *on* for we, people, someone; *vous* to one person; *il / elle* for things",
    needs: [],
    after: [],
    faces: ["choose"],
    placed: "A1",
  },
  "R.stress": {
    module: "pronouns",
    what: "Stress pronouns *moi, toi, lui, elle, nous, vous, eux, elles*: after a preposition, alone, for emphasis, in *c'est moi*, with *-même*",
    needs: ["R.subject"],
    after: [],
    faces: ["gap"],
    placed: "A1–A2",
  },
  "R.do": {
    module: "pronouns",
    what: "Direct object pronouns *me, te, le, la, nous, vous, les*, before the verb; *le / la → l'*",
    needs: ["R.subject", "P.elision"],
    after: [],
    faces: ["transform"],
    placed: "A2",
  },
  "R.io": {
    module: "pronouns",
    what: "Indirect object pronouns *me, te, lui, nous, vous, leur*: for *à* + person; verbs that take *à* (*parler à, téléphoner à, plaire à*) against English",
    needs: ["R.do", "V.verb-prep"],
    after: [],
    faces: ["transform"],
    placed: "A2",
  },
  "R.y": {
    module: "pronouns",
    what: "*y* replaces *à* + place or thing, and *chez / dans / sur* + place: *j'y vais*",
    needs: ["R.io"],
    after: [],
    faces: ["transform"],
    placed: "A2",
  },
  "R.en": {
    module: "pronouns",
    what: "*en* replaces *de* + thing and a quantity: *j'en veux deux*; the number stays",
    needs: ["R.y", "D.de-quantity"],
    after: [],
    faces: ["transform"],
    placed: "A2",
  },
  "R.pronoun-infinitive": {
    module: "pronouns",
    what: "The pronoun goes before the infinitive it belongs to: *je vais le voir*, *je veux lui parler*",
    needs: ["R.io", "V.futur-proche"],
    after: [],
    faces: ["order"],
    placed: "A2",
  },
  "R.pronoun-compound": {
    module: "pronouns",
    what: "With a compound tense the pronoun goes before the auxiliary: *je l'ai vu*, *je lui ai parlé*",
    needs: ["R.io", "V.pc"],
    after: [],
    faces: ["order"],
    placed: "A2",
  },
  "R.pronoun-negative": {
    module: "pronouns",
    what: "Pronouns inside the negation: *je ne le vois pas*, *je ne l'ai pas vu*",
    needs: ["R.pronoun-compound", "G.pas-compound"],
    after: [],
    faces: ["order"],
    placed: "A2",
  },
  "R.pronoun-imperative": {
    module: "pronouns",
    what: "Pronouns after an affirmative command with a hyphen, *me → moi*, *te → toi*; before a negative one: *donne-le-moi, ne me le donne pas*; *vas-y, parles-en* get their *s* back",
    needs: ["R.io", "V.imperative"],
    after: [],
    faces: ["transform"],
    placed: "A2–B1",
  },
  "R.order": {
    module: "pronouns",
    what: "Two pronouns at once: *me / te / se / nous / vous* before *le / la / les* before *lui / leur* before *y* before *en*",
    needs: ["R.pronoun-imperative"],
    after: [],
    faces: ["order"],
    placed: "B1–B2",
  },
  "R.reflexive": {
    module: "pronouns",
    what: "Reflexive pronouns *me, te, se, nous, vous, se*, and the reciprocal reading (*ils se parlent*)",
    needs: ["R.subject"],
    after: [],
    faces: ["gap"],
    placed: "A1–A2",
  },
  "R.neuter-le": {
    module: "pronouns",
    what: "*le* for an idea or an adjective: *je le sais, elle l'est*",
    needs: ["R.do"],
    after: [],
    faces: ["transform"],
    placed: "B1",
  },
  "R.rel-qui-que": {
    module: "pronouns",
    what: "Relatives *qui* (subject) and *que* (object), *qu'* before a vowel; the participle agrees after *que*",
    needs: ["R.do"],
    after: [],
    faces: ["choose", "gap"],
    placed: "A2 (B1 for the agreement)",
  },
  "R.rel-ou": {
    module: "pronouns",
    what: "*où* for where and when: *le jour où*",
    needs: ["R.rel-qui-que"],
    after: [],
    faces: ["gap"],
    placed: "A2–B1",
  },
  "R.rel-dont": {
    module: "pronouns",
    what: "*dont* for *de* + relative: *le livre dont je parle, l'ami dont le père …*",
    needs: ["R.rel-ou", "V.verb-prep"],
    after: [],
    faces: ["gap"],
    placed: "B1",
  },
  "R.ce-qui": {
    module: "pronouns",
    what: "*ce qui, ce que, ce dont* for \"what\"; the mise en relief *ce que je veux, c'est …*",
    needs: ["R.rel-dont"],
    after: [],
    faces: ["choose"],
    placed: "B1",
  },
  "R.rel-compound": {
    module: "pronouns",
    what: "*lequel / laquelle / lesquels / lesquelles* after a preposition, fused with *à* and *de* (*auquel, duquel*); *à qui* for people",
    needs: ["R.rel-dont", "D.contract"],
    after: [],
    faces: ["gap"],
    placed: "B1–B2",
  },
  "R.demonstrative": {
    module: "pronouns",
    what: "*celui / celle / ceux / celles* + *-ci / -là*, *de*, or a relative: *celui qui parle*; *ça / cela / ceci*",
    needs: ["R.rel-qui-que", "D.demonstrative"],
    after: [],
    faces: ["gap"],
    placed: "A2–B1",
  },
  "R.possessive": {
    module: "pronouns",
    what: "*le mien, la tienne, les siens, le nôtre, le leur*",
    needs: ["D.possessive"],
    after: [],
    faces: ["gap"],
    placed: "A2",
  },
  "R.indefinite": {
    module: "pronouns",
    what: "*quelqu'un, quelque chose, personne, rien, tout, tous, chacun, plusieurs, certains, l'un … l'autre, n'importe qui*; adjective after them with *de* and masculine",
    needs: ["D.indef-det"],
    after: [],
    faces: ["gap"],
    placed: "A2–B1",
  },
  "R.interrogative": {
    module: "pronouns",
    what: "*qui, que, quoi, qu'est-ce qui, qu'est-ce que, qui est-ce qui, lequel*",
    needs: ["Q.words"],
    after: [],
    faces: ["choose"],
    placed: "A1–B2",
  },
  "V.pres-er": {
    module: "verbs",
    what: "Présent of *-er* verbs: stem + *-e -es -e -ons -ez -ent*; four of the six sound the same",
    needs: ["R.subject", "P.final"],
    after: [],
    faces: ["gap", "say"],
    placed: "A1",
  },
  "V.pres-etre-avoir": {
    module: "verbs",
    what: "*être* and *avoir* in the présent, as items; *c'est / il y a / j'ai … ans*",
    needs: ["V.pres-er"],
    after: [],
    faces: ["gap", "say"],
    placed: "A1",
  },
  "V.pres-aller-faire": {
    module: "verbs",
    what: "*aller* and *faire*, as items; *aller* for how you are, *faire* for weather and sport",
    needs: ["V.pres-etre-avoir"],
    after: [],
    faces: ["gap"],
    placed: "A1",
  },
  "V.pres-ir": {
    module: "verbs",
    what: "Présent of *-ir* verbs like *finir*: *-is -is -it -issons -issez -issent*",
    needs: ["V.pres-er"],
    after: [],
    faces: ["gap"],
    placed: "A1",
  },
  "V.pres-re": {
    module: "verbs",
    what: "Présent of *-re* verbs like *vendre, attendre*: *-s -s — -ons -ez -ent*; *prendre* and family lose the *d* in the plural (*prenons, prennent*), *mettre* and *battre* drop a *t* in the singular (*je mets*)",
    needs: ["V.pres-ir"],
    after: [],
    faces: ["gap"],
    placed: "A1",
  },
  "V.pres-tir": {
    module: "verbs",
    what: "*partir, sortir, dormir, servir, sentir*: the stem loses its last consonant in the singular (*je pars, nous partons*)",
    needs: ["V.pres-re"],
    after: [],
    faces: ["gap"],
    placed: "A1",
  },
  "V.pres-ouvrir": {
    module: "verbs",
    what: "*ouvrir, offrir, souffrir, découvrir, cueillir* conjugate like *-er* verbs",
    needs: ["V.pres-er"],
    after: [],
    faces: ["gap"],
    placed: "A2",
  },
  "V.pres-spelling": {
    module: "verbs",
    what: "The spelling-change groups: *-cer → ç* and *-ger → ge* before *a / o* (*commençons, mangeons*); *-yer → i* before a silent *e* (*paie / paye* both for *-ayer*); *-eler / -eter* double the consonant (*appelle, jette*) where *acheter, geler, peler* take *è*; *é_er* and *e_er* take *è* in the stressed forms (*préfère, lève*)",
    needs: ["V.pres-er"],
    after: [],
    faces: ["gap"],
    placed: "A1–A2",
  },
  "V.pres-modals": {
    module: "verbs",
    what: "*pouvoir, vouloir, devoir* as items, each with two stems (*peux / pouvons / peuvent*); modal + infinitive; *il faut*",
    needs: ["V.pres-aller-faire"],
    after: [],
    faces: ["gap"],
    placed: "A1",
  },
  "V.pres-venir": {
    module: "verbs",
    what: "*venir, tenir* and derivatives: *viens / venons / viennent*; *venir de* + infinitive for just did",
    needs: ["V.pres-modals"],
    after: [],
    faces: ["gap"],
    placed: "A1",
  },
  "V.pres-savoir-connaitre": {
    module: "verbs",
    what: "*savoir* and *connaître* as items, and the difference (a fact or a skill against a person or a place)",
    needs: ["V.pres-modals"],
    after: [],
    faces: ["gap", "choose"],
    placed: "A2",
  },
  "V.pres-dire-lire-ecrire": {
    module: "verbs",
    what: "*dire, lire, écrire* and family (*vous dites*, *ils lisent*, *nous écrivons*)",
    needs: ["V.pres-re"],
    after: [],
    faces: ["gap"],
    placed: "A1–A2",
  },
  "V.pres-voir-croire-boire": {
    module: "verbs",
    what: "*voir, croire, boire, recevoir* and *-cevoir*: two stems each, *vois / voyons, crois / croyons, bois / buvons, reçois / recevons*",
    needs: ["V.pres-re"],
    after: [],
    faces: ["gap"],
    placed: "A1–A2",
  },
  "V.pres-uire-aindre": {
    module: "verbs",
    what: "*conduire, construire* and *-uire* (*-uis / -uisons*); *craindre, peindre, joindre* (*-ains / -aignons*)",
    needs: ["V.pres-re"],
    after: [],
    faces: ["gap"],
    placed: "A2",
  },
  "V.pres-rest": {
    module: "verbs",
    what: "The rest of the common irregulars as items: *courir, mourir, vivre, suivre, rire, s'asseoir, valoir, acquérir*; the impersonals *falloir, pleuvoir*",
    needs: ["V.pres-uire-aindre"],
    after: [],
    faces: ["gap"],
    placed: "A2–B1",
  },
  "V.pres-3pl": {
    module: "verbs",
    what: "Third-person plural: *ils prennent, ils viennent, ils finissent* — the form that is written and mostly not heard, and the last to become automatic",
    needs: ["V.pres-venir", "P.plural-heard"],
    after: [],
    faces: ["gap", "hear"],
    placed: "— (Bartning & Schlyter, stages 2–5)",
  },
  "V.pronominal": {
    module: "verbs",
    what: "Pronominal verbs: *se lever, s'appeler, se souvenir*; the pronoun agrees with the subject; reflexive, reciprocal and idiomatic uses",
    needs: ["V.pres-er", "R.reflexive"],
    after: [],
    faces: ["gap"],
    placed: "A1",
  },
  "V.participle": {
    module: "verbs",
    what: "The past participle: *-er → -é, -ir → -i, -re → -u*; and the irregular set as items (*eu, été, fait, pris, mis, dit, écrit, vu, bu, lu, su, pu, dû, voulu, venu, ouvert, mort, né, connu, reçu, conduit, peint, vécu, plu, ri, suivi, couru, assis*)",
    needs: ["V.pres-re"],
    after: [],
    faces: ["gap"],
    placed: "A2",
  },
  "V.aux": {
    module: "verbs",
    what: "*avoir* or *être* in the compound tenses: *être* for the verbs of coming and going and change (*aller, venir, arriver, partir, entrer, sortir, monter, descendre, naître, mourir, rester, tomber, retourner, passer, devenir, revenir, rentrer*) and every pronominal verb; *avoir* for the rest",
    needs: ["V.participle", "V.pres-etre-avoir"],
    after: [],
    faces: ["choose"],
    placed: "A1–A2",
  },
  "V.aux-transitive": {
    module: "verbs",
    what: "*monter, descendre, sortir, passer, rentrer, retourner* take *avoir* with a direct object: *j'ai sorti le chien*",
    needs: ["V.aux"],
    after: [],
    faces: ["choose"],
    placed: "B1–B2",
  },
  "V.pc": {
    module: "verbs",
    what: "The passé composé: auxiliary in the présent + participle; the meaning (done, once, over)",
    needs: ["V.aux"],
    after: [],
    faces: ["gap", "transform", "which"],
    placed: "A1–A2",
  },
  "V.pc-agree-etre": {
    module: "verbs",
    what: "With *être* the participle agrees with the subject: *elle est partie, ils sont venus*",
    needs: ["V.pc", "J.agree"],
    after: [],
    faces: ["gap"],
    placed: "A2",
  },
  "V.pc-agree-do": {
    module: "verbs",
    what: "With *avoir* it agrees with a direct object that comes *before*: *la lettre que j'ai écrite, je les ai vues*; with a pronominal verb, only when the reflexive pronoun is the direct object (*elle s'est lavée* but *elle s'est lavé les mains*)",
    needs: ["V.pc-agree-etre", "R.pronoun-compound", "R.rel-qui-que"],
    after: [],
    faces: ["gap"],
    placed: "B1 (B2 for the exceptions)",
  },
  "V.pc-pronominal": {
    module: "verbs",
    what: "Pronominal verbs in the passé composé: *être*, the pronoun before it, *je me suis levé(e)*",
    needs: ["V.pc-agree-etre", "V.pronominal"],
    after: [],
    faces: ["gap"],
    placed: "A2",
  },
  "V.imparfait": {
    module: "verbs",
    what: "The imparfait: the *nous* stem of the présent + *-ais -ais -ait -ions -iez -aient*; *être* has *ét-*; *-cer / -ger* keep the *ç / ge* before *a*",
    needs: ["V.pres-modals", "P.verb-endings"],
    after: ["V.pc"],
    faces: ["gap", "transform"],
    placed: "A2",
  },
  "V.pc-vs-imp": {
    module: "verbs",
    what: "Passé composé against imparfait: the event against the scene; what happened against what was going on, used to happen, or was the case; verbs whose meaning shifts (*je savais / j'ai su*, *je devais / j'ai dû*)",
    needs: ["V.pc", "V.imparfait"],
    after: [],
    faces: ["which", "gap"],
    placed: "A2–B1",
  },
  "V.narration": {
    module: "verbs",
    what: "The past in a story: présent, passé composé and imparfait together; *depuis* with the imparfait",
    needs: ["V.pc-vs-imp"],
    after: [],
    faces: ["gap"],
    placed: "B1",
  },
  "V.futur-proche": {
    module: "verbs",
    what: "*aller* + infinitive for what is about to happen; *être en train de* for what is happening; *venir de* for what just did",
    needs: ["V.pres-aller-faire"],
    after: [],
    faces: ["transform"],
    placed: "A1",
  },
  "V.futur": {
    module: "verbs",
    what: "The futur simple: the infinitive (minus *-e* for *-re*) + *-ai -as -a -ons -ez -ont*; the irregular stems as items (*ser-, aur-, ir-, fer-, viendr-, pourr-, voudr-, devr-, saur-, verr-, enverr-, recevr-, courr-, mourr-, faudr-*); after *quand / dès que* where English uses the présent",
    needs: ["V.pres-er", "P.verb-endings"],
    after: ["V.imparfait"],
    faces: ["gap", "transform"],
    placed: "A2·K B1",
  },
  "V.conditionnel": {
    module: "verbs",
    what: "The conditionnel présent: the futur stem + the imparfait endings; *-rai* against *-rais* is the whole difference on the page, and /e/ against /ɛ/ in the mouth",
    needs: ["V.futur", "V.imparfait", "P.vowel-pairs"],
    after: [],
    faces: ["gap", "hear"],
    placed: "A2·K B1",
  },
  "V.cond-uses": {
    module: "verbs",
    what: "What the conditionnel is for: politeness (*je voudrais, pourriez-vous*), the imagined (*si j'avais le temps, je viendrais*), *devrais* should and *pourrais* could, a report that is not confirmed",
    needs: ["V.conditionnel"],
    after: [],
    faces: ["gap", "which"],
    placed: "A1 (politeness) – B1",
  },
  "V.si-clauses": {
    module: "verbs",
    what: "The three *si* sentences: *si* + présent → présent / futur / impératif; *si* + imparfait → conditionnel; *si* + plus-que-parfait → conditionnel passé; never a futur or conditionnel after *si*",
    needs: ["V.cond-uses", "V.pqp"],
    after: [],
    faces: ["gap", "transform"],
    placed: "B1 (B2 for the third)",
  },
  "V.imperative": {
    module: "verbs",
    what: "The impératif: the *tu, nous, vous* forms of the présent without the pronoun; *-er* verbs (and *aller, ouvrir*) drop the *s* of *tu*; *être / avoir / savoir / vouloir* as items (*sois, aie, sache, veuillez*); negative around the verb",
    needs: ["V.pres-er", "V.pres-etre-avoir"],
    after: [],
    faces: ["gap", "transform"],
    placed: "A1–A2 (B2 for the items)",
  },
  "V.pqp": {
    module: "verbs",
    what: "The plus-que-parfait: auxiliary in the imparfait + participle, for what had already happened",
    needs: ["V.imparfait", "V.pc"],
    after: [],
    faces: ["gap"],
    placed: "B1",
  },
  "V.futur-anterieur": {
    module: "verbs",
    what: "The futur antérieur: auxiliary in the futur + participle; for what will have happened, and for a guess (*il aura oublié*)",
    needs: ["V.futur", "V.pc"],
    after: [],
    faces: ["gap"],
    placed: "B2",
  },
  "V.cond-passe": {
    module: "verbs",
    what: "The conditionnel passé: auxiliary in the conditionnel + participle; regret and reproach (*j'aurais dû, tu aurais pu*)",
    needs: ["V.conditionnel", "V.pc"],
    after: [],
    faces: ["gap"],
    placed: "B2",
  },
  "V.subj-forms": {
    module: "verbs",
    what: "The subjonctif présent: the *ils* stem + *-e -es -e -ions -iez -ent*; *nous / vous* borrow the imparfait forms, so a two-stem verb has two stems here too (*boive / buvions*); the items: *sois, aie, aille, fasse, puisse, sache, veuille, faille, vaille, pleuve*",
    needs: ["V.pres-3pl", "V.imparfait"],
    after: ["V.futur"],
    faces: ["gap"],
    placed: "B1 (forms) · K B2",
  },
  "V.subj-triggers": {
    module: "verbs",
    what: "When the subjonctif is required: after *que* following necessity (*il faut que*), wanting (*je veux que*), feeling (*je suis content que*), doubt (*je ne pense pas que*), and the conjunctions *pour que, bien que, avant que, jusqu'à ce que, à condition que, sans que*; the subject must change, otherwise the infinitive",
    needs: ["V.subj-forms"],
    after: [],
    faces: ["choose", "gap"],
    placed: "B1–B2",
  },
  "V.subj-vs-ind": {
    module: "verbs",
    what: "Indicative after *penser que, croire que, espérer que, dire que* in the affirmative; subjonctif when they are negated or questioned; *après que* takes the indicative",
    needs: ["V.subj-triggers"],
    after: [],
    faces: ["choose"],
    placed: "B1–B2",
  },
  "V.subj-passe": {
    module: "verbs",
    what: "The subjonctif passé for what is already done: *je suis content que tu sois venu*",
    needs: ["V.subj-forms", "V.pc"],
    after: [],
    faces: ["gap"],
    placed: "B2",
  },
  "V.passe-simple": {
    module: "verbs",
    what: "Reading the passé simple: *-a / -èrent* for *-er*, *-it / -irent* and *-ut / -urent* for the rest, *fut, eut, fit, vint*; recognised, never produced",
    needs: ["V.pc", "V.imparfait"],
    after: [],
    faces: ["which"],
    placed: "B2 (recognition) · Inventaire C1",
  },
  "V.gerondif": {
    module: "verbs",
    what: "*en* + present participle for while and by: *en travaillant*; the participle from the *nous* stem + *-ant*, three irregular (*ayant, étant, sachant*)",
    needs: ["V.imparfait"],
    after: [],
    faces: ["transform"],
    placed: "B1",
  },
  "V.participe-present": {
    module: "verbs",
    what: "The participe présent and the verbal adjective: *des enfants dormant …* against *des enfants fatigants*, the adjective agreeing",
    needs: ["V.gerondif"],
    after: [],
    faces: ["choose"],
    placed: "B2",
  },
  "V.infinitif-passe": {
    module: "verbs",
    what: "*avoir / être* + participle after *après*: *après avoir mangé, après être parti(e)*",
    needs: ["V.pc"],
    after: [],
    faces: ["transform"],
    placed: "B2",
  },
  "V.passive": {
    module: "verbs",
    what: "The passive: *être* + participle agreeing with the subject, *par* for the agent; *on* and the pronominal as the ways French avoids it",
    needs: ["V.pc-agree-etre"],
    after: [],
    faces: ["transform"],
    placed: "B1",
  },
  "V.causative": {
    module: "verbs",
    what: "*faire* + infinitive for having something done: *je fais réparer la voiture*; *se faire* + infinitive",
    needs: ["V.pres-aller-faire"],
    after: [],
    faces: ["transform"],
    placed: "B2",
  },
  "V.reported": {
    module: "verbs",
    what: "Reported speech in the present: *que* for a statement, *si* for a yes/no question, *ce que / ce qui* for what, the infinitive for a command",
    needs: ["V.pres-dire-lire-ecrire", "R.ce-qui"],
    after: [],
    faces: ["transform"],
    placed: "B1",
  },
  "V.reported-past": {
    module: "verbs",
    what: "Reported speech in the past: présent → imparfait, passé composé → plus-que-parfait, futur → conditionnel; the time words shift (*demain → le lendemain, hier → la veille*)",
    needs: ["V.reported", "V.pqp", "V.cond-uses"],
    after: [],
    faces: ["transform"],
    placed: "B2",
  },
  "V.verb-prep": {
    module: "verbs",
    what: "Verbs that govern *à* or *de* before an infinitive or a noun (*commencer à, arrêter de, penser à, se souvenir de*), and the ones that take none (*vouloir, pouvoir, aimer*); already shown as chunks on each verb's cards",
    needs: ["V.pres-modals"],
    after: [],
    faces: ["gap"],
    placed: "A2–B2",
  },
  "G.pas": {
    module: "negation",
    what: "*ne … pas* around the conjugated verb; *n'* before a vowel; *si* to say yes to a negative question",
    needs: ["V.pres-er", "P.elision"],
    after: [],
    faces: ["transform"],
    placed: "A1",
  },
  "G.pas-infinitive": {
    module: "negation",
    what: "Both halves before an infinitive: *ne pas fumer*; around the modal otherwise: *je ne veux pas partir*",
    needs: ["G.pas", "V.pres-modals"],
    after: [],
    faces: ["order"],
    placed: "A1–A2",
  },
  "G.others": {
    module: "negation",
    what: "*ne … jamais / plus / rien / personne / pas encore / nulle part*; *personne ne …, rien ne …* as subjects",
    needs: ["G.pas"],
    after: [],
    faces: ["transform"],
    placed: "A1–B1",
  },
  "G.pas-compound": {
    module: "negation",
    what: "The negation around the auxiliary: *je n'ai pas vu*, but *je n'ai vu personne*",
    needs: ["G.others", "V.pc"],
    after: [],
    faces: ["order"],
    placed: "A2",
  },
  "G.que": {
    module: "negation",
    what: "The restrictive *ne … que* for only, and *ne … aucun(e)*, *ne … ni … ni*",
    needs: ["G.others"],
    after: [],
    faces: ["transform"],
    placed: "A2–B1",
  },
  "G.combined": {
    module: "negation",
    what: "Two negations together: *plus jamais, plus rien, jamais personne*",
    needs: ["G.que"],
    after: [],
    faces: ["order"],
    placed: "B1",
  },
  "G.spoken": {
    module: "negation",
    what: "*ne* dropped in speech: *je sais pas*; recognised, and written only in dialogue",
    needs: ["G.pas", "P.e-caduc"],
    after: [],
    faces: ["which"],
    placed: "B1 (Kwiziq)",
  },
  "Q.yes-no": {
    module: "questions",
    what: "Three ways to ask: intonation, *est-ce que*, inversion with a hyphen (*parlez-vous*); *n'est-ce pas*",
    needs: ["V.pres-er", "P.questions"],
    after: [],
    faces: ["transform"],
    placed: "A1",
  },
  "Q.words": {
    module: "questions",
    what: "*qui, que / quoi, où, quand, comment, pourquoi, combien (de)*, each with *est-ce que* or inversion",
    needs: ["Q.yes-no"],
    after: [],
    faces: ["gap"],
    placed: "A1",
  },
  "Q.quel": {
    module: "questions",
    what: "*quel / quelle / quels / quelles* + noun, and as an exclamation (*quelle surprise !*)",
    needs: ["Q.words", "J.agree"],
    after: [],
    faces: ["gap"],
    placed: "A2",
  },
  "Q.inversion-t": {
    module: "questions",
    what: "Inversion with *il / elle / on* after a vowel takes *-t-*: *parle-t-il, y a-t-il*; with a noun subject the pronoun is repeated (*Marie parle-t-elle*)",
    needs: ["Q.yes-no", "P.liaison-must"],
    after: [],
    faces: ["transform"],
    placed: "A2",
  },
  "Q.inversion-compound": {
    module: "questions",
    what: "Inversion in the passé composé and with a pronominal verb: *as-tu vu, t'es-tu levé*",
    needs: ["Q.inversion-t", "V.pc"],
    after: [],
    faces: ["transform"],
    placed: "A2–B1",
  },
  "Q.qu-est-ce": {
    module: "questions",
    what: "*qu'est-ce qui* (subject) against *qu'est-ce que* (object), *qui est-ce qui / que*",
    needs: ["Q.words"],
    after: [],
    faces: ["choose"],
    placed: "A2",
  },
  "Q.lequel": {
    module: "questions",
    what: "*lequel / laquelle / lesquels / lesquelles* for which one",
    needs: ["Q.quel"],
    after: [],
    faces: ["gap"],
    placed: "B2",
  },
  "Q.indirect": {
    module: "questions",
    what: "The indirect question: *je me demande si …, dis-moi où …, ce que*",
    needs: ["Q.words", "V.reported"],
    after: [],
    faces: ["transform"],
    placed: "B1",
  },
  "C.place": {
    module: "connectors",
    what: "*à, en, au, aux, dans, chez, sur, sous, devant, derrière, entre, à côté de, en face de, près de, loin de*; *à* for a city, *en / au / aux* for a country by gender",
    needs: ["D.countries"],
    after: [],
    faces: ["choose"],
    placed: "A1",
  },
  "C.transport": {
    module: "connectors",
    what: "*à* against *en* with transport: *à pied, à vélo, en train, en voiture*",
    needs: ["C.place"],
    after: [],
    faces: ["choose"],
    placed: "A1",
  },
  "C.time-markers": {
    module: "connectors",
    what: "*depuis* (still going), *il y a* (ago), *pendant* (a span), *pour* (a planned span), *dans* (from now), *en* (how long it takes), *dès, à partir de*",
    needs: ["N.tens-units"],
    after: [],
    faces: ["choose", "gap"],
    placed: "A1–B1",
  },
  "C.depuis-tense": {
    module: "connectors",
    what: "*depuis* takes the présent where English takes the perfect; the passé composé only in the negative",
    needs: ["C.time-markers", "V.pc"],
    after: [],
    faces: ["choose"],
    placed: "A2–B1",
  },
  "C.en-dans": {
    module: "connectors",
    what: "*en* against *dans* with places and with time",
    needs: ["C.time-markers"],
    after: [],
    faces: ["choose"],
    placed: "A1–A2",
  },
  "C.prep-infinitive": {
    module: "connectors",
    what: "*pour* + infinitive for purpose; *avant de*, *sans*, *au lieu de*, *afin de* + infinitive",
    needs: ["V.pres-modals"],
    after: [],
    faces: ["gap"],
    placed: "A1–B2",
  },
  "C.cause": {
    module: "connectors",
    what: "Cause: *parce que, à cause de, grâce à, car, comme, puisque, en raison de, faute de*",
    needs: ["C.prep-infinitive"],
    after: [],
    faces: ["choose"],
    placed: "A2–B2",
  },
  "C.consequence": {
    module: "connectors",
    what: "Consequence: *donc, alors, c'est pourquoi, par conséquent, si bien que, tellement … que*",
    needs: ["C.cause"],
    after: [],
    faces: ["choose"],
    placed: "A2–B2",
  },
  "C.opposition": {
    module: "connectors",
    what: "Opposition and concession: *mais, alors que, par contre, en revanche, pourtant, cependant, malgré, bien que* + subjonctif, *même si* + indicative, *quand même*",
    needs: ["C.consequence", "V.subj-triggers"],
    after: [],
    faces: ["choose"],
    placed: "A2–B2",
  },
  "C.purpose-condition": {
    module: "connectors",
    what: "Purpose and condition: *pour que, afin que, à condition que, pourvu que* + subjonctif; *au cas où* + conditionnel",
    needs: ["C.opposition", "V.subj-triggers"],
    after: [],
    faces: ["choose"],
    placed: "B1–B2",
  },
  "C.chronology": {
    module: "connectors",
    what: "Ordering a story: *d'abord, puis, ensuite, après, enfin, finalement*; *la veille, le lendemain, d'ici*",
    needs: ["V.narration"],
    after: [],
    faces: ["order"],
    placed: "A2–B1",
  },
  "S.exclamation": {
    module: "sentences",
    what: "*quel …!, que …!, comme …!*",
    needs: ["Q.quel"],
    after: [],
    faces: ["transform"],
    placed: "A2",
  },
  "S.emphasis": {
    module: "sentences",
    what: "Putting a thing first: *ce qui / ce que … c'est …*, *moi, je …*, *c'est … qui / que*",
    needs: ["R.ce-qui", "R.stress"],
    after: [],
    faces: ["transform"],
    placed: "B1",
  },
  "S.nominalisation": {
    module: "sentences",
    what: "The noun from the verb for a headline or a title: *arriver → l'arrivée, développer → le développement*",
    needs: ["D.gender-endings"],
    after: [],
    faces: ["gap"],
    placed: "B1",
  },
  "S.tu-vous": {
    module: "sentences",
    what: "*tu* against *vous*, and what it does to the whole sentence: the verb, the possessive, the pronoun",
    needs: ["R.subject", "D.possessive"],
    after: [],
    faces: ["transform"],
    placed: "A1 (socio-cultural in the Inventaire)",
  },
  "S.avoir-idioms": {
    module: "sentences",
    what: "*avoir faim / soif / chaud / froid / peur / besoin de / envie de / raison / tort / mal à / … ans* — states English says with *be*",
    needs: ["V.pres-etre-avoir"],
    after: [],
    faces: ["gap"],
    placed: "A1–A2",
  },
  "S.impersonal": {
    module: "sentences",
    what: "*il faut, il y a, il fait (beau), il est (tard), il s'agit de, il vaut mieux*",
    needs: ["V.pres-modals"],
    after: [],
    faces: ["gap"],
    placed: "A1–B1",
  },
} as const satisfies Record<string, RuleSpec>;

export type RuleId = keyof typeof RULES;

export const RULE_IDS: readonly RuleId[] = Object.keys(RULES) as RuleId[];

export const isRuleId = (value: unknown): value is RuleId =>
  typeof value === 'string' && value in RULES;

/** The rule, for an id that may have come from a record. */
export const ruleOf = (id: string): RuleSpec | null => (isRuleId(id) ? RULES[id] : null);
